# Generated by Django 3.1 on 2023-08-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='username1',
        ),
    ]
