# Generated by Django 3.1 on 2023-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_app', '0003_auto_20230821_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabledata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=500)),
                ('width', models.CharField(max_length=500)),
                ('height', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=500)),
                ('volume', models.CharField(max_length=500)),
            ],
        ),
    ]
